<?php

use Phpro\SoapClient\Soap\ClassMap\ClassMapCollection;
use Phpro\SoapClient\Soap\ClassMap\ClassMap;

return new ClassMapCollection([
    new ClassMap('AssignOrUpdateIPAddressRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\AssignOrUpdateIPAddressRequest::class),
    new ClassMap('AssignOrUpdateIPAddressResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\AssignOrUpdateIPAddressResponse::class),
    new ClassMap('EditLinePayStatusPerAcctRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\EditLinePayStatusPerAcctRequest::class),
    new ClassMap('EditLinePayStatusPerAcctResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\EditLinePayStatusPerAcctResponse::class),
    new ClassMap('EditLinePayStatusRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\EditLinePayStatusRequest::class),
    new ClassMap('EditLinePayStatusResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\EditLinePayStatusResponse::class),
    new ClassMap('EditTerminalRatingRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\EditTerminalRatingRequest::class),
    new ClassMap('EditTerminalRatingResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\EditTerminalRatingResponse::class),
    new ClassMap('EditTerminalRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\EditTerminalRequest::class),
    new ClassMap('EditTerminalResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\EditTerminalResponse::class),
    new ClassMap('GetLinePayStatusByOpAcctIdRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetLinePayStatusByOpAcctIdRequest::class),
    new ClassMap('GetLinePayStatusByOpAcctIdResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetLinePayStatusByOpAcctIdResponse::class),
    new ClassMap('GetModifiedTerminalsRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetModifiedTerminalsRequest::class),
    new ClassMap('GetModifiedTerminalsResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetModifiedTerminalsResponse::class),
    new ClassMap('GetProvisioningStatusRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetProvisioningStatusRequest::class),
    new ClassMap('GetProvisioningStatusResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetProvisioningStatusResponse::class),
    new ClassMap('GetSessionInfoRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetSessionInfoRequest::class),
    new ClassMap('GetSessionInfoResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetSessionInfoResponse::class),
    new ClassMap('GetTerminalAuditTrailRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalAuditTrailRequest::class),
    new ClassMap('GetTerminalAuditTrailResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalAuditTrailResponse::class),
    new ClassMap('GetTerminalDetailsRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalDetailsRequest::class),
    new ClassMap('GetTerminalDetailsResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalDetailsResponse::class),
    new ClassMap('GetTerminalLatestNetworkRegistrationRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalLatestNetworkRegistrationRequest::class),
    new ClassMap('GetTerminalLatestNetworkRegistrationResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalLatestNetworkRegistrationResponse::class),
    new ClassMap('GetTerminalLatestRegistrationRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalLatestRegistrationRequest::class),
    new ClassMap('GetTerminalLatestRegistrationResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalLatestRegistrationResponse::class),
    new ClassMap('GetTerminalRatingRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalRatingRequest::class),
    new ClassMap('GetTerminalRatingResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalRatingResponse::class),
    new ClassMap('GetTerminalsByImsiRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalsByImsiRequest::class),
    new ClassMap('GetTerminalsByImsiResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalsByImsiResponse::class),
    new ClassMap('GetTerminalsByMsisdnRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalsByMsisdnRequest::class),
    new ClassMap('GetTerminalsByMsisdnResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalsByMsisdnResponse::class),
    new ClassMap('GetTerminalsBySecureSimIdRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalsBySecureSimIdRequest::class),
    new ClassMap('GetTerminalsBySecureSimIdResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\GetTerminalsBySecureSimIdResponse::class),
    new ClassMap('QueueTerminalRatePlanRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\QueueTerminalRatePlanRequest::class),
    new ClassMap('QueueTerminalRatePlanResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\QueueTerminalRatePlanResponse::class),
    new ClassMap('RemoveRatePlanFromQueueRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\RemoveRatePlanFromQueueRequest::class),
    new ClassMap('RemoveRatePlanFromQueueResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\RemoveRatePlanFromQueueResponse::class),
    new ClassMap('SendCancelLocationRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\SendCancelLocationRequest::class),
    new ClassMap('SendCancelLocationResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\SendCancelLocationResponse::class),
    new ClassMap('SimRmaExchangeRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\SimRmaExchangeRequest::class),
    new ClassMap('SimRmaExchangeResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\SimRmaExchangeResponse::class),
    new ClassMap('TransferSimsToAccountRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\TransferSimsToAccountRequest::class),
    new ClassMap('TransferSimsToAccountResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\TransferSimsToAccountResponse::class),
    new ClassMap('TransferTrialSimsToAccountRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\TransferTrialSimsToAccountRequest::class),
    new ClassMap('TransferTrialSimsToAccountResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\TransferTrialSimsToAccountResponse::class),
    new ClassMap('UpdateSecureSimCredentialsRequest', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\UpdateSecureSimCredentialsRequest::class),
    new ClassMap('UpdateSecureSimCredentialsResponse', \BrightNucleus\JasperClient\SoapTypes\TerminalClient\UpdateSecureSimCredentialsResponse::class),
]);
